name: Build Android and iOS
on:
  push:
    branches:
      - main
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn install
      - name: Run tests
        run: |
          yarn test
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn install
      - name: Make gradlew executable
        run: |
          chmod +x ./android/gradlew
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease -PMYAPP_UPLOAD_STORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}' -PMYAPP_UPLOAD_KEY_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}'
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
  build-ios:
    needs: install-and-test
    runs-on: macOS-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn install
      - name: Install pod dependencies
        run: |
          cd ios && pod install
      - name: Build app
        run: |       
          cd ios && xcodebuild -workspace myApp.xcworkspace -scheme myApp archive -archivePath myApp.xcarchive -allowProvisioningUpdates
          xcodebuild -exportArchive -archivePath ./myApp.xcarchive -exportPath . -exportOptionsPlist myApp/Info.plist
          mv myApp.ipa ../myApp.ipa -sdk iphonesimulator
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: myapp.ipa
          path: ios/build/
  
